backend:
  name: git-gateway
  branch: main  # or whatever your main branch is

media_folder: "static/images"  # This is where images will be stored
public_folder: "/images"  # Public URL for images

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"  # This is where your blog posts will be stored
    create: true  # Allows you to create new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Creates a clean URL based on the date
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
